import {
  ClipboardList,
  FlaskConical,
  Activity,
  HeartPulse,
  Scan,
  Dumbbell,
  Scissors,
  BedDouble,
  Syringe,
  Bandage,
  Layers,
} from "lucide-react";
import type { ModuleConfig } from "./types";

const defaultStatus = { status: "EN_ATTENTE", montant: "0", notes: "" };

export const RECEPTION_CONFIG: ModuleConfig = {
  key: "reception",
  table: "reception",
  title: "Réception",
  subtitle: "Accueil, orientation et enregistrement des bénéficiaires",
  icon: ClipboardList,
  modulePermission: "reception",
  dateField: "date_reception",
  fields: [
    { key: "motif", label: "Motif de visite", type: "text", required: true, showInTable: true },
    { key: "service_destine", label: "Service destiné", type: "select", required: true, options: ["Consultation", "Kinésithérapie", "Laboratoire", "EG", "ECG", "Radiologie", "Chirurgie", "Hospitalisation", "Pharmacie", "Pansement", "Plâtre", "Soins infirmiers"], showInTable: true },
    { key: "priorite", label: "Priorité", type: "select", options: ["NORMAL", "URGENT", "CRITIQUE"], showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, motif: "", service_destine: "Consultation", priorite: "NORMAL" },
  paymentType: "Réception",
  createLabel: "Nouvelle réception",
};

export const LABORATORY_CONFIG: ModuleConfig = {
  key: "laboratoire",
  table: "laboratory_exams",
  title: "Laboratoire",
  subtitle: "Analyses et examens biologiques",
  icon: FlaskConical,
  modulePermission: "laboratoire",
  dateField: "date_prescription",
  examCategory: "Laboratoire",
  fields: [
    { key: "type_examen", label: "Type d'examen", type: "select", required: true, options: ["NFS", "Glycémie", "VS2", "Créatinine", "Urée", "Bilan hépatique", "Bilan lipidique", "Groupe sanguin", "VIH", "Paludisme", "Autre"], showInTable: true },
    { key: "priorite", label: "Priorité", type: "select", options: ["NORMAL", "URGENT", "CRITIQUE"], showInTable: true },
    { key: "resultats", label: "Résultats", type: "textarea", showInTable: false },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_examen: "NFS", priorite: "NORMAL" },
  paymentType: "Laboratoire",
  createLabel: "Nouvel examen",
};

export const EG_CONFIG: ModuleConfig = {
  key: "eg",
  table: "eg_exams",
  title: "Électroencéphalogramme (EEG)",
  subtitle: "Examens EEG et activité cérébrale",
  icon: Activity,
  modulePermission: "eg",
  dateField: "date_examen",
  examCategory: "EEG",
  fields: [
    { key: "type_examen", label: "Type d'examen", type: "select", required: true, options: ["EEG standard", "EEG prolongé", "EEG de sommeil", "EEG avec photostimulation", "Autre"], showInTable: true },
    { key: "resultats", label: "Résultats", type: "textarea", showInTable: false },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_examen: "EEG standard" },
  paymentType: "EG",
  createLabel: "Nouvel examen EG",
};

export const ECG_CONFIG: ModuleConfig = {
  key: "ecg",
  table: "ecg_exams",
  title: "Électrocardiogramme (ECG)",
  subtitle: "Examens cardiaques et rythmologie",
  icon: HeartPulse,
  modulePermission: "ecg",
  dateField: "date_examen",
  examCategory: "ECG",
  fields: [
    { key: "type_examen", label: "Type d'examen", type: "select", required: true, options: ["ECG 12 dérivations", "ECG de repos", "ECG d'effort", "Holter ECG", "Autre"], showInTable: true },
    { key: "frequence_cardiaque", label: "Fréquence cardiaque", type: "number", showInTable: true },
    { key: "resultats", label: "Résultats", type: "textarea", showInTable: false },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_examen: "ECG 12 dérivations", frequence_cardiaque: "" },
  paymentType: "ECG",
  createLabel: "Nouvel examen ECG",
};

export const RADIOLOGY_CONFIG: ModuleConfig = {
  key: "radiologie",
  table: "radiology_exams",
  title: "Radiologie",
  subtitle: "Imagerie médicale et diagnostics radiologiques",
  icon: Scan,
  modulePermission: "radiologie",
  dateField: "date_examen",
  examCategory: "Radiologie",
  fields: [
    { key: "type_examen", label: "Type d'examen", type: "select", required: true, options: ["Radiographie", "Échographie", "Scanner", "IRM", "Mammographie", "Autre"], showInTable: true },
    { key: "zone_anatomique", label: "Zone anatomique", type: "text", required: true, showInTable: true },
    { key: "resultats", label: "Compte-rendu", type: "textarea", showInTable: false },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_examen: "Radiographie", zone_anatomique: "" },
  paymentType: "Radiologie",
  createLabel: "Nouvel examen",
};

export const KINESITHERAPIE_CONFIG: ModuleConfig = {
  key: "kinesitherapie",
  table: "kinesitherapie_sessions",
  title: "Kinésithérapie",
  subtitle: "Séances de rééducation fonctionnelle et motrice",
  icon: Dumbbell,
  modulePermission: "kinesitherapie",
  dateField: "date_seance",
  isWorkflowService: true,
  fields: [
    { key: "type_seance", label: "Type de séance", type: "select", required: true, options: ["Rééducation motrice", "Rééducation neurologique", "Rééducation respiratoire", "Massothérapie", "Électrothérapie", "Rééducation post-op", "Autre"], showInTable: true },
    { key: "objectifs", label: "Objectifs", type: "textarea", showInTable: false },
    { key: "exercices", label: "Exercices réalisés", type: "textarea", showInTable: false },
    { key: "evaluation_douleur", label: "Échelle douleur (0-10)", type: "number", showInTable: true },
    { key: "duree_minutes", label: "Durée (min)", type: "number", showInTable: true },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_seance: "Rééducation motrice", duree_minutes: "45", evaluation_douleur: "" },
  paymentType: "Kinésithérapie",
  createLabel: "Nouvelle séance",
};

export const CHIRURGIE_CONFIG: ModuleConfig = {
  key: "chirurgie",
  table: "surgeries",
  title: "Chirurgie",
  subtitle: "Interventions chirurgicales et suivi opératoire",
  icon: Scissors,
  modulePermission: "chirurgie",
  dateField: "date_intervention",
  isWorkflowService: true,
  fields: [
    { key: "type_intervention", label: "Type d'intervention", type: "text", required: true, showInTable: true },
    { key: "diagnostic_preop", label: "Diagnostic pré-op", type: "textarea", showInTable: false },
    { key: "procedure", label: "Procédure", type: "textarea", showInTable: false },
    { key: "salle", label: "Salle", type: "text", showInTable: true },
    { key: "duree_minutes", label: "Durée (min)", type: "number", showInTable: true },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_intervention: "", salle: "", duree_minutes: "" },
  paymentType: "Chirurgie",
  createLabel: "Nouvelle intervention",
};

export const HOSPITALISATION_CONFIG: ModuleConfig = {
  key: "hospitalisation",
  table: "hospitalizations",
  title: "Hospitalisation",
  subtitle: "Prise en charge hospitalière et suivi des lits",
  icon: BedDouble,
  modulePermission: "hospitalisation",
  dateField: "date_admission",
  isWorkflowService: true,
  amountField: "montant_journalier",
  fields: [
    { key: "motif_admission", label: "Motif d'admission", type: "text", required: true, showInTable: true },
    { key: "chambre", label: "Chambre", type: "text", showInTable: true },
    { key: "lit", label: "Lit", type: "text", showInTable: true },
    { key: "diagnostic", label: "Diagnostic", type: "textarea", showInTable: false },
    { key: "montant_journalier", label: "Tarif journalier (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { status: "EN_COURS", montant_journalier: "0", notes: "", motif_admission: "", chambre: "", lit: "", diagnostic: "" },
  paymentType: "Hospitalisation",
  createLabel: "Nouvelle admission",
};

export const SOINS_INFIRMIERS_CONFIG: ModuleConfig = {
  key: "soins_infirmiers",
  table: "nursing_care",
  title: "Soins Infirmiers",
  subtitle: "Soins infirmiers et suivi des bénéficiaires",
  icon: Syringe,
  modulePermission: "soins_infirmiers",
  dateField: "date_soin",
  isWorkflowService: true,
  fields: [
    { key: "type_soin", label: "Type de soin", type: "select", required: true, options: ["Injection", "Perfusion", "Toilette", "Surveillance", "Prise de constantes", "Administration médicament", "Autre"], showInTable: true },
    { key: "description", label: "Description", type: "textarea", showInTable: false },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { ...defaultStatus, type_soin: "Surveillance", description: "" },
  paymentType: "Soins infirmiers",
  createLabel: "Nouveau soin",
};

export const PLATRES_CONFIG: ModuleConfig = {
  key: "plâtres",
  table: "plasters",
  title: "Plâtres",
  subtitle: "Pose et suivi des immobilisations plâtrées",
  icon: Layers,
  modulePermission: "plâtres",
  dateField: "date_pose",
  isWorkflowService: true,
  fields: [
    { key: "zone_corps", label: "Zone du corps", type: "text", required: true, showInTable: true },
    { key: "type_platre", label: "Type de plâtre", type: "select", required: true, options: ["Plâtre court", "Plâtre long", "Attelle", "Orthèse", "Body cast", "Autre"], showInTable: true },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { status: "EN_COURS", montant: "0", notes: "", zone_corps: "", type_platre: "Plâtre court" },
  paymentType: "Plâtre",
  createLabel: "Nouveau plâtre",
};

export const PANSEMENTS_CONFIG: ModuleConfig = {
  key: "pansements",
  table: "dressings",
  title: "Pansements",
  subtitle: "Soins de plaies et pansements thérapeutiques",
  icon: Bandage,
  modulePermission: "pansements",
  dateField: "date_pansement",
  isWorkflowService: true,
  fields: [
    { key: "zone_corps", label: "Zone du corps", type: "text", required: true, showInTable: true },
    { key: "type_pansement", label: "Type de pansement", type: "select", required: true, options: ["Simple", "Stérile", "Compressif", "Hydrocolloïde", "Alginate", "Autre"], showInTable: true },
    { key: "montant", label: "Montant (CDF)", type: "number", showInTable: true },
    { key: "status", label: "Statut", type: "select", options: ["EN_ATTENTE", "EN_COURS", "TERMINE", "ANNULE"] },
    { key: "notes", label: "Notes", type: "textarea", showInTable: false },
  ],
  defaultForm: { status: "TERMINE", montant: "0", notes: "", zone_corps: "", type_pansement: "Simple" },
  paymentType: "Pansement",
  createLabel: "Nouveau pansement",
};
